Feature/create command
aalvarezwindey/Open-LISA-Server pull request #24
Opened 2022-08-11 03:37 UTC by gabyrobles93

2022-08-11 03:38 UTC, gabyrobles93 commented on data_test/database/commands.db.seed.json
>    "data": [
Reduje este file a unos pocos comandos representativos.
Tenia que editarlo para agregar los ids a los elementos
Además, tenia alguna inconsistencia porque al agregar un elemento, la base de datos rompia el file y perdia el correcto formato JSON.

2022-08-11 03:40 UTC, gabyrobles93 commented on data_test/database/commands.db.seed.json
>    "data": [
La BBDD toma el primer elemento como fuente de verdad en cuanto al esquema. Si el 1er elemento es un CLIBCommand entonces espera que cualquier cosa que metas tenga un path de clib. Esto haria que rompa al intentar agregar un SCPI Command. Tenemos que cambiar la base de datos lamentablemente, no veo forma de configurarla para ignorar el esquema.

Un walkaround podría ser agregar ese campo en NULL para los comandos SCPI, pero ya lo probé y termina rompiendo en otros puntos del código por NPE.

![image](https://user-images.githubusercontent.com/12588243/184061176-d64827d5-05c9-427e-bc1f-7ae1bb12cd15.png)

2022-08-11 03:41 UTC, gabyrobles93 commented on data_test/database/commands.db.seed.json
>    "data": [
Una solución copada sería separar la BBDD de comandos en CLIBCommands y SCPICommands, pero no se cuanto esfuerzo implica eso, imagino que bastante y se romperian bocha de tests.

2022-08-11 03:44 UTC, gabyrobles93 commented on open_lisa/repositories/commands_repository.py
> +        command_json = super().get_by_id(id)
TODO: Handlear el caso en que no exista el comando. Modelar y devolver una excepción de CommandNotFoundError análoga a la que existe para instrumentos.

2022-08-11 03:47 UTC, gabyrobles93 commented on open_lisa/tests/test_integration.py
> +    # la inserción del siguiente comando SCPI fallará por violación de esquema
Necesitamos revisar este punto.
No pueden convivir 2 test integrales que den de alta comandos SCPI y CLIB, ya que esta esta condición clave que menciono en el comment.

2022-08-11 14:16 UTC, aalvarezwindey-peya requested changes
Muy buen laburo gabo! Dejo algunos comentarios

2022-08-11 14:16 UTC, aalvarezwindey-peya commented on open_lisa/api/api.py
> +                            self._commands_repository, self._instruments_repository)
El instrument repository o instrument ya tiene un commands_repository

quizás basta con `Instrument.add_command`  y que el `Instrument` haga uso de su `CommandsRepository` interno

2022-08-11 14:16 UTC, aalvarezwindey-peya commented on open_lisa/protocol/server_protocol.py
> +        if lower(command_type) == lower(CommandType.SCPI.name):
Por qué `lower` ? Esto nos agregaría `numpy` como dependencia al proyecto
Para comparar `enums` lo que hacemos en otras partes del proyecto es `str(CommandType.SCPI)`, eso devuelve el name me parece (devuelve  lo que esté implementado en `def __str__()` de la clase `CommandType` y ese valor en string es el que debería ser mandado desde la SDK

2022-08-11 14:16 UTC, aalvarezwindey-peya commented on open_lisa/protocol/server_protocol.py
> +        command_type = self._message_protocol.receive_msg()
Acá si querés se puede unificar el instrument_id y el command_type en el `command_payload` o `command_creation_request`, así te queda todo en un solo mensaje intercambiado entre la SDK y Server (ese enfoque tomamos en la creación de instrumentos)

2022-08-11 14:16 UTC, aalvarezwindey-peya commented on open_lisa/protocol/server_protocol.py
> +            new_command = commands_repository.create_command(command_payload, pyvisa_resource)
Como mencioné arriba creo que haría que `server_protocol` llame a Instrument para crear un Command, entonces cualquier lógica de negocio crea en la capa de `domain` (en este caso `Instrument`) y no en el protocolo de comunicación, con lógica de negocio me refiero:
- validar que el instrumento sea del type del comando que se quiere crear
- hacer uso del command repository que ya tiene cada instrumento
- [validar que ya no tiene un comando con el mismo nombre?]

2022-08-11 14:16 UTC, aalvarezwindey-peya commented on open_lisa/repositories/commands_repository.py
> +        command_type = lower(command_json["type"])
idem anterior, haría simplemente str(type)

2022-08-11 14:16 UTC, aalvarezwindey-peya commented on open_lisa/repositories/commands_repository.py
> +        if command_type == lower(CommandType.SCPI.value):
Me parece que esto se repite con `__deserialize_commands` me parece (que dicho sea de paso el nombre correcto debería ser `__deserialize_command` sin S, se me pasó eso... podemos aprovechar y ajustarlo)

2022-08-11 15:48 UTC, garoblesmeli commented on open_lisa/protocol/server_protocol.py
> +        if lower(command_type) == lower(CommandType.SCPI.name):
En la bbdd teniamos en mayus, y el enum estaba en minus, lo puse para evitar esos dolores de cabeza
quiza String tenga un comparador que ignore el case

2022-08-11 15:49 UTC, garoblesmeli commented on open_lisa/protocol/server_protocol.py
> +        command_type = self._message_protocol.receive_msg()
Si, de hecho en el mismo payload de comando ya tenes embebido el tipo y el instrument_id, se puede sacar directamente de ahi. Tomo esa optimización

2022-08-11 23:19 UTC, aalvarezwindey-peya commented on open_lisa/protocol/server_protocol.py
> +        if lower(command_type) == lower(CommandType.SCPI.name):
se guarda en mayus porque los repositories hacen `str(enum)` y eso te da el `name` del enum que están en mayus

De todos modos mi comentario iba más porque tu IDE te importo el método `lower` de `numpy` que sería cacho overkill tener numpy para hacer un lower case.
Existe `string.lower()` en python, pero al ser enums tendrías que hacer `str(enum).lower()` que es medio lo mismo que simplemente hacer `str(enum)` y comparar

2022-08-11 23:38 UTC, garoblesmeli commented on open_lisa/api/api.py
> +                            self._commands_repository, self._instruments_repository)
Mmmm entiendo que quedaria mas limpio, pero:
1. Instrument no tiene ni InstrumentRepository ni CommandRepository
2. InstrumentRepository si tiene a CommandRepository, pero sería raro que InstrumentRepository tenga una primitiva para agregar un comando creo yo...

2022-08-11 23:44 UTC, aalvarezwindey-peya commented on open_lisa/api/api.py
> +                            self._commands_repository, self._instruments_repository)
Cierto, pensé que había dejado CommandRepository en `Instrument`... pero le terminé dejando una lista de comandos `[Command]`

La otra sería que en `Instrument.add_command` hagas un `new CommandRepository` y las validaciones de negocio te quedan en Instrument... pero tampoco estoy seguro si es tanto más limpio (quizás te queda más fácil de testear siendo que Instrument tiene algunos tests ya y ServerProtocol no)... démosle para adelante como a vos te parezca mejor

2022-08-11 23:50 UTC, garoblesmeli commented on open_lisa/protocol/server_protocol.py
> +        if lower(command_type) == lower(CommandType.SCPI.name):
Donatello

2022-08-11 23:51 UTC, garoblesmeli commented on open_lisa/protocol/server_protocol.py
> +        command_type = self._message_protocol.receive_msg()
Done

2022-08-11 23:51 UTC, garoblesmeli commented on open_lisa/protocol/server_protocol.py
> +            new_command = commands_repository.create_command(command_payload, pyvisa_resource)
Esto hoy no es posible por lo que comente mas arriba

2022-08-11 23:52 UTC, garoblesmeli commented on open_lisa/repositories/commands_repository.py
> +        command_type = lower(command_json["type"])
Done

2022-08-11 23:55 UTC, garoblesmeli commented on open_lisa/repositories/commands_repository.py
> +        if command_type == lower(CommandType.SCPI.value):
MAAAL chabon, fixed.

2022-08-12 13:41 UTC, aalvarezwindey-peya commented on open_lisa/tests/utils.py
> +    if os.path.exists("data_test/database"):
Cambiamos `distutils` por. `shutil` a proposito? tengo el recuerdo que lo habia probado con `shutil` y me fallaba... no será eso el problema?

2022-08-12 13:41 UTC, aalvarezwindey-peya reviewed
Deje un comentario sobre el util de seed, por otro lado veo que estás commiteando  la eliminación del contenido `data_test` queremos eso?

2022-08-12 13:42 UTC, garoblesmeli commented on open_lisa/tests/utils.py
> +    if os.path.exists("data_test/database"):
con distutils tuve todo tipo de errores random

2022-08-12 13:44 UTC, aalvarezwindey-peya commented on open_lisa/tests/utils.py
> +    if os.path.exists("data_test/database"):
Asquencio

2022-08-20 21:59 UTC, aalvarezwindey commented on open_lisa/domain/command/clib_command.py
> +                "lib_file_name": os.path.basename(self.lib_file_name)
Acá deberíamos retornar el filename + cualquier subcarpeta interna en lib_base_path, no? @gabyrobles93 

Ejemplo
`<ROOT_DIR>/.../clibs/highspeedcam/my_lib.dll`

Al front/sdk le debería llegar `/highspeedcam/my_lib.dll`

2022-08-20 23:07 UTC, aalvarezwindey approved these changes

2022-08-20 23:36 UTC, gabyrobles93 commented on open_lisa/domain/command/clib_command.py
> +                "lib_file_name": os.path.basename(self.lib_file_name)
Donatello

2022-08-20 23:36 UTC, merged